version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 15
    - package-ecosystem: 'gitsubmodule'
      directory: '/lib'
      schedule:
          interval: 'daily'
    - package-ecosystem: 'gitsubmodule'
      directory: '/src/ui/impl/webview/lib'
      schedule:
          interval: 'daily'