language: cpp
compiler: gcc
sudo: required
dist: bionic
addons:
  apt:
    packages:
      - git
      - golang-go
      - qt5-default
      - libqt5x11extras5-dev

git:
  depth: false

install:
  - go get qpm.io/qpm

script:
  - ~/go/bin/qpm install
  - mkdir build
  - cd build
  - qmake ..
  - make
