on:
    push:
        branches: [master]
        paths-ignore:
            - "**/README.md"
            - "**/docs/**"
            - "**/release_windows.yml"
            - '**/compile_linux.yml'
            - '**/codeql-analysis-python.yml'
    pull_request:
        branches: [master]

name: Build Flatpak
jobs:
    flatpak-builder:
        runs-on: ubuntu-20.04
        container:
            image: bilelmoussaoui/flatpak-github-actions:kde-5.15
            options: --privileged

        steps:
            - uses: actions/checkout@v2
            - uses: bilelmoussaoui/flatpak-github-actions@v2
              with:
                  bundle: "soundux.flatpak"
                  manifest-path: "io.github.Soundux.yml"
