on:
    push:
        branches: [master]
        paths-ignore:
            - "**/README.md"
            - "**/compile_windows.yml"
            - "**/compile_linux.yml"
            - "**/.all-contributorsrc"
            - "**/upload_full_src.yml"
            - "**/windows_debug.yml"
    pull_request:
        branches: [master]

name: Build Flatpak
jobs:
    flatpak-builder:
        runs-on: ubuntu-20.04
        container:
            image: bilelmoussaoui/flatpak-github-actions:gnome-3.38
            options: --privileged

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - name: Install build dependencies
              run: "sudo apt-get update && sudo apt-get install git build-essential cmake libx11-dev libxi-dev libwnck-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev"

            - name: Compile Embed-Helper
              run: "cd src/ui/impl/webview/lib/webviewpp/embed-helper && mkdir build && cd build && cmake .. && cmake --build . --config Release && ./embed_helper ../../../soundux-ui"

            - uses: bilelmoussaoui/flatpak-github-actions@v2
              with:
                  bundle: "soundux.flatpak"
                  manifest-path: "deployment/flatpak/io.github.Soundux.yml"