on:
    push:
        branches: [ master ]
        paths-ignore:
        - '**/README.md'
        - '**/docs/**'
        - '**/release_windows.yml'
    pull_request:
        branches: [ master ]

name: Build on Linux
jobs:
    build-linux:
        runs-on: ubuntu-20.04
        strategy:
          fail-fast: false
          matrix:
            language: [ 'cpp' ]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: 'true'

            - name: Install Qt
              uses: jurplel/install-qt-action@v2
              with:
                version: '5.15.2'
                dir: '${{ github.workspace }}/qt/'

            - name: Install other build dependencies
              run: 'sudo apt-get install libx11-dev libxi-dev fuse imagemagick'
            
            # Initializes the CodeQL tools for scanning.
            #- name: Initialize CodeQL
            #  uses: github/codeql-action/init@v1
            #  with:
            #    languages: ${{ matrix.language }}

            - name: Compile
              run: 'mkdir build && cd build && cmake .. && make'

            #- name: Perform CodeQL Analysis
            #  uses: github/codeql-action/analyze@v1

            - name: Create AppImage - Copy necessary files (1/2)
              run: 'mkdir AppImage && cd AppImage && cp ../build/soundux . && cp ../src/soundux.desktop . && cp ../icon.png . && mv icon.png soundux.png && mogrify -resize 256x256 soundux.png'

            # This is just a test I have to find out where the qt/{plugins,qml} folder is
            - name: Create AppImage - Copy necessary files (2/2)
              run: 'cd AppImage && mkdir usr && mkdir ./usr/lib && mkdir ./usr/lib/qt && cp -r ../qt/Qt/5.15.2/gcc_64/plugins ./usr/lib/qt && cp -r ../qt/Qt/5.15.2/gcc_64/plugins ./usr/lib/qml'

            - name: Create AppImage - Download Linuxdeploy
              run: 'cd AppImage && wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage && chmod a+x linuxdeploy-x86_64.AppImage'

            - name: Create AppImage - Run LinuxDeploy
              run: 'cd AppImage && ./linuxdeploy-x86_64.AppImage --executable=soundux --icon-file=soundux.png --desktop-file=soundux.desktop --appdir AppDir --output appimage'

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v2.2.1
              with:
                  name: AppImage
                  path: 'AppImage/*.AppImage'
