on:
    push:
        branches: [ master ]
        paths-ignore:
        - '**/README.md'
        - '**/docs/**'
    pull_request:
        branches: [ master ]

name: Build on Linux
jobs:
    build-linux:
        runs-on: ubuntu-20.04
        strategy:
          fail-fast: false
          matrix:
            language: [ 'cpp' ]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: 'true'

            - name: Install Qt
              uses: jurplel/install-qt-action@v2
              with:
                version: '5.15.2'
                dir: '${{ github.workspace }}/qt/'

            - name: Install other build dependencies
              run: 'sudo apt-get install libx11-dev libxi-dev fuse'
            
            # Initializes the CodeQL tools for scanning.
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v1
              with:
                languages: ${{ matrix.language }}

            - name: Compile
              run: 'mkdir build && cd build && cmake .. && make'
            
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v1

            - name: Find QML
              run: 'sudo apt-get install mlocate && updatedb && locate builtins.qmltypes'

            - name: Make AppImage
              run: 'mkdir -p AppDir/usr/{bin,share} && mkdir -p AppDir/usr/share/{applications,icons} && mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps && cp build/soundux AppDir/usr/bin && cp src/soundux.desktop AppDir/usr/share/applications && cp icon.png AppDir/usr/share/icons/hicolor/256x256/apps/soundux.png && wget https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-587-x86_64.AppImage && chmod +x appimagetool-587-x86_64.AppImage && ./appimagetool-587-x86_64.AppImage -s deploy AppDir/usr/share/applications/*.desktop && QMLDIR=dirname $(locate builtins.qmltypes | head -n 1) && cp -r $QMLDIR AppDir/usr/libx86_64-linux-gnu/ && chmod +x AppDir/usr/lib64/ld-linux-x86-64.so.2 && VERSION=1.0 ./appimagetool-587-x86_64.AppImage ./AppDir'

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v2.2.1
              with:
                  name: AppImage
                  path: Soundux-1.0-x86_64.AppImage