on:
    push:
        branches: [ master ]
        paths-ignore:
        - '**/README.md'
        - '**/docs/**'

name: Compile
jobs:
    build-linux:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: 'true'

            - name: Install Dependencies
              run: 'sudo apt-get install qt5-default libx11-dev libqt5x11extras5-dev qtquickcontrols2-5-dev qtdeclarative5-dev libxi-dev qml-module-qtquick2 qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-dialogs qml-module-qtquick-layouts qml-module-qtquick-window2 qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel'
            
            - name: Compile
              run: 'mkdir build && cd build && cmake .. && make'