on:
    push:
        branches: [ master ]
        paths-ignore:
        - '**/README.md'
        - '**/docs/**'
        - '**/release_windows.yml'
    pull_request:
        branches: [ master ]

name: Build on Linux
jobs:
    build-linux:
        runs-on: ubuntu-20.04
        strategy:
          fail-fast: false
          matrix:
            language: [ 'cpp' ]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: 'true'

            - name: Install Qt
              uses: jurplel/install-qt-action@v2
              with:
                version: '5.15.2'
                dir: '${{ github.workspace }}'

            - name: Install other build dependencies
              run: 'sudo apt-get install libx11-dev libxi-dev'
            
            # Initializes the CodeQL tools for scanning.
            - name: Initialize CodeQL
             uses: github/codeql-action/init@v1
             with:
               languages: ${{ matrix.language }}

            - name: Compile
              run: 'mkdir build && cd build && cmake .. && make'

            - name: Perform CodeQL Analysis
             uses: github/codeql-action/analyze@v1