on:
    push:
        branches: [ master ]
        paths-ignore:
        - '**/README.md'
        - '**/docs/**'

name: Build and Release
jobs:
    build-windows:
        runs-on: windows-latest
        env:
          working-directory: .
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: 'true'
                
            - name: Install Qt
              uses: jurplel/install-qt-action@v2
              with:
                dir: '${{ github.workspace }}/qt/'
            
            - name: Compile
              run: 'mkdir build && cd build && cmake .. && cmake --build . --target ALL_BUILD --config Release'

            - name: Windeploy
              run: 'cd build/Release && windeployqt --release --qmldir ../../src soundux.exe'

            - name: Install InnoSetup  
              uses: crazy-max/ghaction-chocolatey@v1
              with: 
                args: install innosetup -y

            - name: Install Sed  
              uses: crazy-max/ghaction-chocolatey@v1
              with: 
                args: install sed -y
            
            - name: Install 7zip  
              uses: crazy-max/ghaction-chocolatey@v1
              with: 
                args: install 7zip -y
            
            - name: Install Wget  
              uses: crazy-max/ghaction-chocolatey@v1
              with: 
                args: install wget -y

            - name: Run Sed
              run: '&"${Env:ProgramData}\chocolatey\bin\sed.exe" -i ''s%\$PATH%D:\\a\\Soundux\\Soundux%'' src/Soundux.iss'
            
            - name: Download VB-Cable
              run: '&"${Env:ProgramData}\chocolatey\bin\wget.exe" https://download.vb-audio.com/Download_CABLE/VBCABLE_Driver_Pack43.zip'
                
            - name: Unpack VB-Cable
              run: '&"${Env:ProgramData}\chocolatey\bin\7z.exe" x .\VBCABLE_Driver_Pack43.zip -o*'
                
            - name: Run InnoSetup
              run: '&"${Env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe" src/Soundux.iss'

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v2.2.1
              with:
                  name: Release
                  path: build/Release
            
            - name: Upload Installer Artifact
              uses: actions/upload-artifact@v2.2.1
              with:
                  name: Installer
                  path: src/Output/setup.exe