on:
    push:
        branches: [ master ]
        paths-ignore:
        - '**/README.md'
        - '**/docs/**'

name: Build and Release
jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: 'true'
                
            - name: Install Qt
              uses: jurplel/install-qt-action@v2
              with:
                dir: '${{ github.workspace }}/qt/'
            
            - name: Compile
              run: 'mkdir build && cd build && cmake .. && cmake --build . --target ALL_BUILD --config Release'

            - name: Windeploy
              run: 'cd build/Release && windeployqt --release --qmldir ../../src soundux.exe'

            - name: Archive production artifacts
              uses: actions/upload-artifact@v2.2.1
              with:
                  name: Release
                  path: build/Release

            - name: Install InnoSetup  
              uses: crazy-max/ghaction-chocolatey@v1
              with: 
                args: install innosetup -y

            - name: Create Installer
              run: '&${Env:ProgramFiles(x86)}\Inno\ Setup\ 6\ISCC.exe src/Soundux.iss'